# Generated by Django 3.1.3 on 2020-12-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent_slug', models.ForeignKey(blank=True, db_column='parent_slug', null=True, on_delete=django.db.models.deletion.PROTECT, to='rate.region')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.IntegerField()),
                ('dest_code', models.ForeignKey(db_column='dest_code', on_delete=django.db.models.deletion.PROTECT, related_name='dest_codes', to='rate.port')),
                ('orig_code', models.ForeignKey(db_column='orig_code', on_delete=django.db.models.deletion.PROTECT, related_name='origin_codes', to='rate.port')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.AddField(
            model_name='port',
            name='parent_slug',
            field=models.ForeignKey(db_column='parent_slug', on_delete=django.db.models.deletion.PROTECT, to='rate.region'),
        ),
    ]
